runtime: go111
instance_class: F1

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /heartbeat
  script: auto
  secure: always

- url: /(.*)
  static_files: static/\1
  upload: static/(.*)
  secure: always

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 50
