runtime: go
api_version: go1.8
instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 3m

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /heartbeat
  script: _go_app

- url: /(.*)
  static_files: static/\1
  upload: static/(.*)
