runtime: nodejs12
instance_class: F1

default_expiration: '30d'

handlers:
- url: /(.*)
  script: auto
  secure: always

automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 50
