runtime: go
api_version: go1.8

handlers:
- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /heartbeat
  script: _go_app

- url: /(.*)
  static_files: static/\1
  upload: static/(.*)
